modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://github.com/antiphysika/omnicomp-mod/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://raw.githubusercontent.com/antiphysika/omnicomp-mod/main/updates.json"
#displayURL="https://github.com/antiphysika/omnicomp-mod"
#logoFile="omnicomp-mod.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

#[[mixins]]
#config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="dynamic_asset_generator"
    type="required"
    versionRange="${dynassetgen_version}"
    ordering="NONE"
    side="CLIENT"

#
# vim: ts=2 sw=2 et fdm=marker :